### ISSUE TITLE
MY-WM->TH bug

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1473]
```
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 130, in launch_parsers
    **parser_kwargs)
  File "/home/electricitymap/parsers/MY_WM.py", line 309, in fetch_exchange
    hvdc_hidden_values = extract_hidden_values(hvdc_switch_req)
  File "/home/electricitymap/parsers/MY_WM.py", line 176, in extract_hidden_values
    viewstategenerator = soup.find("input", attrs={'id': '__VIEWSTATEGENERATOR'})['value']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by systemcatch** [comment]
For this one we could make a try/except that catches this and generates a warning rather than an error.
