### ISSUE TITLE
AR bug

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1476]
```
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 130, in launch_parsers
    **parser_kwargs)
  File "/home/electricitymap/parsers/AR.py", line 763, in fetch_production
    gdt = get_datetime(session=None)
  File "/home/electricitymap/parsers/AR.py", line 599, in get_datetime
    find_hour = timesoup.find("option", selected="selected", value="1").getText()
AttributeError: 'NoneType' object has no attribute 'getText'
```

**Comment by systemcatch** [comment]
This is related to #811, current best explanation is that the page/app is offline for about 4 hours starting at midnight.
