### ISSUE TITLE
Costa Rica does not have data available between 12am-1am

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1477]
```
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 130, in launch_parsers
    **parser_kwargs)
  File "/home/electricitymap/parsers/CR.py", line 191, in fetch_production
    df = pd.read_html(response.text, match=CHARACTERISTIC_NAME, skiprows=1, index_col=0)[0]
  File "/usr/local/lib/python3.6/site-packages/pandas/io/html.py", line 915, in read_html
    keep_default_na=keep_default_na)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/html.py", line 749, in _parse
    raise_with_traceback(retained)
  File "/usr/local/lib/python3.6/site-packages/pandas/compat/__init__.py", line 385, in raise_with_traceback
    raise exc.with_traceback(traceback)
ValueError: No tables found matching pattern 'Angostura'
```

**Comment by systemcatch** [comment]
This has happened every day between 7am and 8am for the past 90 days. There is no data table available in that timespan.  Costa Rica's timezone is UTC-6 and with daylight savings in Europe atm it correlates perfectly with no data being available for 12-1am in Costa Rica.

Possible solutions;

- If current time being requested is between 12-1am local time then get data for the previous day.
- Ignore it since the data backfills properly later on anyway. (assuming I'm right @corradio ?)

**Comment by corradio** [comment]
You're right assuming the CR parser returns a list of datapoints (in opposition to a single one)

**Comment by systemcatch** [comment]
Yes it returns a list of them.
