### ISSUE TITLE
Costa Rica page has changed and now errors

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap-contrib#1561]
```
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 131, in launch_parsers
    **parser_kwargs)
  File "/home/contrib/parsers/CR.py", line 178, in fetch_production
    jsf_view_state = soup.select('#javax.faces.ViewState')[0]['value']
IndexError: list index out of range
```

https://github.com/tmrowco/electricitymap-contrib/blob/86f06791f2292c8a20e383a4642ced8b16083333/parsers/CR.py#L178

**Comment by systemcatch** [comment]
Right this is what I'm sending at this point.

```python
response2 = r.post(url, headers=headers, data=data)
```

headers some of which I've manually set.
```python
{'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Host': 'apps.grupoice.com', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0', 'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'https://apps.grupoice.com/CenceWeb/CencePosdespachoNacional.jsf', 'Connection': 'keep-alive', 'Cookie': 'oam.Flash.RENDERMAP.TOKEN=4nxq9fcw8; JSESSIONID=0000LlGMCHNs4gUrVWu0I0tlxx1:1cjolulg9'}
```

data
```python
[('formPosdespacho_SUBMIT', '1'),
 ('formPosdespacho:txtFechaInicio_input', '16/08/2018'),
 ('formPosdespacho:pickFecha', ''),
 ('formPosdespacho:j_id_1c_selection', ''),
 ('formPosdespacho:j_id_1c_scrollState', '0,0'),
 ('javax.faces.ViewState', 'vXHdw7Ci6MYtEY1bLr4PUvqpCNHXWOVTHVJFJrnSQrUSzDdh')]
```

The cookies are being handled correctly but still no table in the response. @jarek can you take a look as well?
