### ISSUE TITLE
Corsica is missing from Entsoe domain mappings

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap-contrib#1645]
If this is expected maybe we could add an exception to avoid cluttering up the logger with errors.

```python
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 174, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/feeder/lib/fetch_data.py", line 172, in <lambda>
    **parser_kwargs))
  File "/home/contrib/parsers/ENTSOE.py", line 992, in fetch_exchange
    domain1 = ENTSOE_DOMAIN_MAPPINGS[zone_key1]
KeyError: 'FR-COR'
```

**Comment by lorrieq** [comment]
Looking at the domain mapping for `FR-COR->IT-CNO` says `FR-COR`'s code is `10Y1001A1001A893` (which is labelled as `Italy_Saco_DC` in the ENTSOE [guide](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html)). 
Maybe we just need to add a mapping to `ENTSOE_EXCHANGE_DOMAIN_OVERRIDE`: 
`'FR-COR->IT-SAR': ['10Y1001A1001A893', ENTSOE_DOMAIN_MAPPINGS['IT-SAR']]`
