### ISSUE TITLE
Issues on Formentera

### ISSUE THREAD

**Issue by eitreb** [tmrowco/electricitymap-contrib#1992]
There's something broken on the Formentera parser: it often shows no production at all, or incomplete generation data

**Comment by systemcatch** [comment]
It is sort of working again, the logger shows the error that was occuring.

https://kibana.electricitymap.org/app/kibana#/doc/96f67170-0c49-11e9-85c1-1d63df8c862c/logstash-2019.09.30/doc?id=ZT5sgm0B9KdT5TbKMT10&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))

```python
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 172, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/feeder/lib/fetch_data.py", line 170, in <lambda>
    **parser_kwargs))
  File "/home/contrib/parsers/ES_IB.py", line 66, in fetch_consumption
    island_data = fetch_island_data(zone_key, ses)
  File "/home/contrib/parsers/ES_IB.py", line 28, in fetch_island_data
    formentera_data = Formentera(session, verify=False).get_all()
  File "/usr/local/lib/python3.6/site-packages/ree/balearic/formentera.py", line 13, in get_all
    return self.get(None, False)
  File "/usr/local/lib/python3.6/site-packages/ree/balearic/formentera.py", line 10, in get
    return super(self.__class__, self).get("FORMENTERA", "Europe/Madrid", "Baleares", date, last)
  File "/usr/local/lib/python3.6/site-packages/ree/core/scraper.py", line 24, in get
    for value in self._request(url):
  File "/usr/local/lib/python3.6/site-packages/ree/core/scraper.py", line 77, in _request
    raise ResponseCodeException
ree.core.exceptions.ResponseCodeException
```
Can't see the response code which is annoying, most likely the service was down.

**Comment by eitreb** [comment]
Nothing changed, something isn't working, I doubt Formentera switches from no consumption to 100% gas to 100% solar suddenly…

![Screenshot_20191002-172747__01](https://user-images.githubusercontent.com/45237862/66058472-bb9cf380-e53a-11e9-9548-f75ba4be0698.jpg)

**Comment by systemcatch** [comment]
Looks absolutely all over the place, the data source (https://demanda.ree.es/visiona/baleares/formentera/total) seems alright though.

**Comment by eitreb** [comment]
Now it looks like consumption data are ok
