### ISSUE TITLE
Error in CY parser

### ISSUE THREAD

**Issue by FelixDQ** [tmrowco/electricitymap-contrib#2661]
Sorry I didn't catch this when reviewing. The new CY parser uses a function that is only available in python 3.7 (parsers run with python 3.6)

The error:
```
Traceback (most recent call last):
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 175, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 173, in <lambda>
    **parser_kwargs))
  File "/home/src/electricitymap/contrib/parsers/CY.py", line 136, in fetch_production
    'datetime': datetime.datetime.fromisoformat(
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

This is the line:
https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/CY.py#L136

CC @veqtrus 
ref https://github.com/tmrowco/electricitymap-contrib/pull/2637

**Comment by veqtrus** [comment]
Does it have to be a python datetime or could I just return an arrow object? Is there a preferred way to convert?

**Comment by FelixDQ** [comment]
It has to be a datetime, but you can just do `.datetime` on the arrow object to get the datettime object.
https://arrow.readthedocs.io/en/stable/#properties
