### ISSUE TITLE
GB (ELEXON parser) exchanges broken

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2829]
~~Kibana:~~

>~~Expected 19 fields in FUELINST report, got 22
>Traceback (most recent call last):  
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 176, in launch_parsers   objs = res.get(timeout)  
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get      raise self._value  
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker      result = (True, func(*args, **kwds))  
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 174, in <lambda>      **parser_kwargs))  
  File "/home/src/electricitymap/contrib/parsers/ELEXON.py", line 289, in fetch_production      wind = _fetch_wind(target_datetime)  
  File "/home/src/electricitymap/contrib/parsers/ELEXON.py", line 253, in _fetch_wind      report['expected_fields'], len(df.columns)))  
ValueError: Expected 19 fields in FUELINST report, got 22~~
  
***Edit:** Fixed in #2828. Exchanges still broken*

Exchanges with FR, NL and IE are broken too. Exchanges with BE and GB-NIR are still working, but those use ENTSOE and the GB_NIR parser, respectively

>Expected 8 fields in INTERFUELHH report, got 11

>Traceback (most recent call last):  
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 176, in launch_parsers      objs = res.get(timeout)  
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get      raise self._value  
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker      result = (True, func(*args, **kwds))  
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 174, in <lambda>      **parser_kwargs))  
  File "/home/src/electricitymap/contrib/parsers/ELEXON.py", line 277, in fetch_exchange      logger)  
  File "/home/src/electricitymap/contrib/parsers/ELEXON.py", line 130, in parse_exchange     report['expected_fields'], field_count))  
ValueError: Expected 8 fields in INTERFUELHH report, got 11  

Same error for those three exchanges

**Comment by jarek** [comment]
might have been fixed by https://github.com/tmrowco/electricitymap-contrib/pull/2828 ?

**Comment by q--** [comment]
From a cursory look generation mix will probably work, but I'm not sure if #2828 has also fixed the exchanges.

**Comment by ilfrich** [comment]
The new exchanges (3 of them, 2 to FR, 1 to NO) haven't been added yet.

**Comment by ilfrich** [comment]
Now I have :)
